global using Waste.Domain.Models;
global using Waste.Infrastructure.Data;
global using Waste.Domain.ValueObjects;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using System.Reflection;
global using Waste.Domain.Enums;