version: '3.4'

services:

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  message-broker:
    image: rabbitmq:management

  diet.api:
    image: ${DOCKER_REGISTRY-}dietapi
    build:
      context: .
      dockerfile: Services/Diet/Diet.API/Dockerfile

  waste.api:
    image: ${DOCKER_REGISTRY-}wasteapi
    build:
      context: .
      dockerfile: Services/Waste/Waste.API/Dockerfile

  bacpatient.api:
    image: ${DOCKER_REGISTRY-}bacpatientapi
    build:
      context: .
      dockerfile: Services/BacPatient/BacPatient.API/Dockerfile
  visit.api:
    image: ${DOCKER_REGISTRY-}visitapi
    build:
      context: .
      dockerfile: Services/Visit/Visit.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile