version: '3.4'

services:

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  message-broker:
    image: rabbitmq:management

  # diet.api:
  #   image: ${DOCKER_REGISTRY-}dietapi
  #   build:
  #     context: .
  #     dockerfile: Services/Diet/Diet.API/Dockerfile

  # waste.api:
  #   image: ${DOCKER_REGISTRY-}wasteapi
  #   build:
  #     context: .
  #     dockerfile: Services/Waste/Waste.API/Dockerfile

  medication.api:
    image: ${DOCKER_REGISTRY-}medicationapi
    build:
      context: .
      dockerfile: Services/Medication/Medication.API/Dockerfile

  # bacpatient.api:
  #   image: ${DOCKER_REGISTRY-}bacpatientapi
  #   build:
  #     context: .
  #     dockerfile: Services/BacPatient/BacPatient.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

