version: '3.4'

services:

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2019-latest

  message-broker:
    image: rabbitmq:management

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  waste.api:
    image: ${DOCKER_REGISTRY-}wasteapi
    build:
      context: .
      dockerfile: Services/Waste/Waste.API/Dockerfile

  prescription.api:
    image: ${DOCKER_REGISTRY-}prescriptionapi
    build:
      context: .
      dockerfile: Services/Prescription/Prescription.API/Dockerfile